Algoritmo "calculoHoraTrabalhada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2026
Var
// Seção de Declarações das variáveis 
valorHora, horasT, salReceber: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Informe a quantidade de horas trabalhadas por semana: ")
leia(horasT)
escreval("Informe o valor pago por hora trabalhada R$: ")
leia(valorHora)
salReceber <- (valorHora*HorasT)
escreval("Seu salário mensal é R$: ", salReceber:8:2)

Fimalgoritmo