Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2026
Var
// Seção de Declarações das variáveis 
valor, calcValor: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Informe um valor: ")
   leia(valor)
   calcValor <- (valor * 5)
   escreval("O valor multiplicado por 5 é: ",calcValor)


Fimalgoritmo