Algoritmo "Calcular idade"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2026
Var
// Seção de Declarações das variáveis 
anoNasc, anoAtual, calcIdade: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Informe o ano de seu nascimento: ")
   leia(anoNasc)
   escreval("Informe o ano atual: ")
   leia(anoAtual)
   calcIdade <- (anoAtual-AnoNasc)

   escreval("Sua idade é: ",calcIdade)

Fimalgoritmo