Algoritmo "Leia numero inteiro"

Var
// Seção de Declarações das variáveis 
numero, sucessor, antecessor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Informe um numero inteiro")
leia(numero)
sucessor <- numero+1
antecessor <- numero-1
limpatela
escreval("O numero informado é: ",numero)
escreval("Seu sucessor é: ",sucessor)
escreval("Seu antecessor é: ",antecessor)


Fimalgoritmo